# docker-compose.yml
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_BUCKET=health
      - INFLUXDB_ORG=archimed
      - INFLUXDB_RETENTION=7d

networks:
  default:
    external:
      name: archimed-network
